package vn.loi.learning.desktop.ui.contentlibrary

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import vn.loi.learning.desktop.ui.search.SearchField
import vn.loi.learning.desktop.ui.search.SearchRefinementBar

@Composable fun LessonBrowserCard(uiState:LessonBrowserUiState,onClose:()->Unit,onSelectLesson:(String)->Unit,onClearLessonSelection:()->Unit,onStartStudy:(String)->Unit,onQueryChanged:(String)->Unit,onClearQuery:()->Unit,onFilterChanged:(LessonBrowserFilter)->Unit,onSortChanged:(LessonBrowserSort)->Unit,modifier:Modifier=Modifier){val selected=uiState.selectedLesson;Card(modifier.fillMaxWidth()){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){if(selected==null){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(uiState.libraryName,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text(lessonBrowserSearchSummary(uiState).label)};OutlinedButton(onClick=onClose){Text("Back")}};SearchField(uiState.query,"Search lessons",lessonBrowserSearchSummary(uiState),onQueryChanged,onClearQuery);val refinements=uiState.refinementState();SearchRefinementBar(lessonBrowserRefinementPresentation(uiState),!refinements.isDefault,{onQueryChanged("");onFilterChanged(LessonBrowserFilter.ALL);onSortChanged(LessonBrowserSort.PACKAGE_ORDER)});Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){LessonBrowserFilter.entries.forEach{f->FilterChip(uiState.filter==f,{onFilterChanged(f)},{Text(f.label)})}};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){LessonBrowserSort.entries.forEach{s->FilterChip(uiState.sort==s,{onSortChanged(s)},{Text(s.label)})}};if(uiState.visibleLessons.isEmpty())Text(lessonBrowserEmptySearchMessage(uiState)) else uiState.visibleLessons.forEach{lesson->LessonRow(lesson){onSelectLesson(lesson.id)}}}else{Column(verticalArrangement=Arrangement.spacedBy(12.dp)){Text(selected.title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);if(selected.hasHierarchy)Text(selected.hierarchyPath);Text(selected.primaryText);selected.translatedText?.let{Text(it)};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton(onClick=onClearLessonSelection){Text("Back")};Button(onClick={onStartStudy(selected.id)}){Text("Start Study")}}}}}}}
@Composable private fun LessonRow(lesson:LessonBrowserItem,onOpen:()->Unit){val a=resolveLessonBrowserItemAccessibility(lesson);Card(Modifier.fillMaxWidth().semantics(mergeDescendants=true){contentDescription=a.contentDescription},colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){if(lesson.hasHierarchy)Text(lesson.hierarchyPath);Text(a.title,fontWeight=FontWeight.SemiBold);if(lesson.primaryText!=lesson.title)Text(lesson.primaryText);lesson.translatedText?.let{Text(it)};Text("${lesson.type} · ${lesson.learningItemCount} learning items");Button(onClick=onOpen){Text("Open")}}}}
