package vn.loi.learning.application.contentpackaging

enum class PackageImportProgressStage {
    RESOLVING,
    SCANNING,
    READING_METADATA,
    OPENING_MEDIA,
    INDEXING_MEDIA,
    EXTRACTING_MEDIA,
    IMPORTING_CONTENT,
    VALIDATING_MEDIA,
    PACKAGE_INSTALLED,
    CONTENT_IMPORTED,
    VALIDATING_TOPIC_STRUCTURE,
    PREPARING_CONTENT_RECORDS,
    SAVING_CONTENT,
    SAVING_LEARNING_ITEMS,
    REGISTERING_PACKAGE,
    UPDATING_LIBRARY,
    REFRESHING_PROJECTIONS,
    COMPLETED
}
