package vn.loi.learning.application.decision

/**
 * Adaptive decision generated by InstructionalDecisionEngine.
 */
data class AdaptiveDecision(
    val decisionId: String,
    val action: AdaptiveAction,
    val targetSceneType: String,
    val newDifficultyLevel: Int,
    val rationale: String
)
